<?php

/**
 * @file
 * Custom module that alter forms.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */

function mymodule_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state){
    $form['site_phone'] = array(
        '#type' => 'tel',
        '#title' => t('Site phone'),
        '#default_value' => Drupal::config('system.site')->get('phone'),
    );

    $form['#submit'][] = 'mymodule_form_system_site_information_phone_submit';

}

/**
 * Form callback to save site_phone
 * @param array $form
 * @param FormStateInterface $form_state
 */

function mymodule_form_system_site_information_phone_submit(array &$form, FormStateInterface $form_state){
    $config = Drupal::configFactory()->getEditable('system.site');
    $config->set('phone', $form_state->getValue('site_phone'))->save();

}